- name: Generate artifact, copy artifact & sql file to files directory
  hosts: localhost
  connection: local
  become: yes
  vars:
    project_path: /home/devopsadmin/multitier-webstack/app
  tasks:
    - name: Install  jdk, maven, git
      apt:
        name: "{{item}}"
        state: present
        update_cache: yes
      loop:
        - git
        - openjdk-8-jdk
        - maven


    - name: Clone source code from github
      git:
        repo: 'https://github.com/steventongsf/multitier-webstack'
        dest: /home/devopsadmin/multitier-webstack
        version: master
      register: git_status

    - name: create files directory
      file:
        path: files/
        state: directory


    - name: mvn install command to build artifact
      command: "mvn -e install"
      args:
        chdir: "{{ project_path }}"
      #when: git_status.changed
      register: mvn_info


    - name: Copy artifacts to files directory
      copy:
        src: "{{item}}"
        dest: files/ROOT.war
      with_fileglob:  "{{ project_path }}/target/*.war"

    - name: Copy SQL file to files directory
      copy:
        src:  "{{ project_path }}/src/main/resources/db_backup.sql"
        dest: files/db_backup.sql

